# Generated by Django 5.2.6 on 2026-05-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='audited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='activity_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.importbatch'),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='scope',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
