# Generated by Django 5.2.6 on 2026-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_normalizedrecord_audited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
