# Generated by Django 5.2.6 on 2026-05-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_normalizedrecord_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizedrecord',
            name='route',
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='activity_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
